In [2]:
import numpy as np
a=np.array([0,1,2,3])
print(a)

[0 1 2 3]


In [5]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [6]:
L=range(100)
%timeit [i**2 for i in L]

75.1 µs ± 5.72 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [8]:
a=np.arange(100)
%timeit a**2

1.44 µs ± 133 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [9]:
#1-dimension array
a=np.array([1,2,3,4])

In [11]:
a.ndim

1

In [13]:
a.shape

(4,)

In [14]:
len(a)

4

In [17]:
#2D array
b=np.array([[1,2,3,4],[4,5,6,7]])
b

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [18]:
b.shape

(2, 4)

In [19]:
b.ndim

2

In [20]:
len(b) #returns size of first dimension

2

In [22]:
#3D array
c= np.array([[[1,2],[2,3]],[[4,5],[5,6]]])
c

array([[[1, 2],
        [2, 3]],

       [[4, 5],
        [5, 6]]])

In [23]:
c.ndim

3

In [24]:
len(c)

2

In [25]:
c.shape

(2, 2, 2)

In [ ]:
1D array -> Vector
2D array-> Matrix
nD array-> Tensor

In [28]:
b=np.arange(1,10,2)
b

array([1, 3, 5, 7, 9])

In [30]:
a=np.linspace(0,1,6)
a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [31]:
a=np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [32]:
b=np.zeros((3,3))
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [34]:
c=np.eye(3,2)
c

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [38]:
a=np.diag([1,2,3,4])
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [40]:
#random no.
np.random.rand(4) #uniform distributed random no.

array([0.10047113, 0.20039135, 0.14190234, 0.15554382])

In [41]:
np.random.randn(4)  #Gaussian dist. random no.

array([-1.84674297, -0.0896753 ,  0.33629475, -1.82387224])

In [47]:
a=np.arange(10)
print(a)
a.dtype

[0 1 2 3 4 5 6 7 8 9]


dtype('int32')

In [48]:
a=np.arange(10,dtype='float')
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [52]:
d=np.array([1+2j,2+4j]) #complex datatype
d

array([1.+2.j, 2.+4.j])

In [56]:
b=np.array([True,False,True,False])
b.dtype

dtype('bool')

In [59]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
a[1:8:2]

array([1, 3, 5, 7])

In [62]:
a[5:]=10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [63]:
b=np.arange(5)
a[5:]=b[::-1]
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

In [65]:
a=np.random.randint(0,20,15)
a

array([ 5, 18,  2, 19,  7, 19, 14, 10, 19,  0, 15, 19, 10, 19,  5])

In [66]:
mask = (a%2==0)
extract_a_mask = a[mask]
extract_a_mask

array([18,  2, 14, 10,  0, 10])

In [68]:
a[mask]=-1
a

array([ 5, -1, -1, 19,  7, 19, -1, -1, 19, -1, 15, 19, -1, 19,  5])

In [70]:
#indexing with an array of integers
a=np.arange(0,100,10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [72]:
a[[2,3,4,2,6]] #indexing can be done with an array of integers

array([20, 30, 40, 20, 60])

In [76]:
a[[9,7]] = -200
a

array([   0,   10,   20,   30,   40,   50,   60, -200,   80, -200])

In [77]:
a[5]

50

In [80]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [81]:
a+1

array([2, 3, 4, 5])

In [82]:
a*2

array([2, 4, 6, 8])

In [84]:
b=np.ones(4) +1
b

array([2., 2., 2., 2.])

In [85]:
a-b

array([-1.,  0.,  1.,  2.])

In [86]:
a*b

array([2., 4., 6., 8.])

In [87]:
a

array([1, 2, 3, 4])

In [89]:
#Matrix multiplication
c=np.diag([1,2,3,4])

In [90]:
c*c

array([[ 1,  0,  0,  0],
       [ 0,  4,  0,  0],
       [ 0,  0,  9,  0],
       [ 0,  0,  0, 16]])

In [91]:
c.dot(c)

array([[ 1,  0,  0,  0],
       [ 0,  4,  0,  0],
       [ 0,  0,  9,  0],
       [ 0,  0,  0, 16]])

In [93]:
a=np.array([1,2,3,4])
b=np.array([2,5,6,4])
a==b

array([False, False, False,  True])

In [94]:
a>b

array([False, False, False, False])

In [95]:
c=np.array([1,2,3,4])

In [96]:
np.array_equal(a,b)

False

In [97]:
np.array_equal(a,c)  #arraywise comparisions

True

In [100]:
#Logical operations
a=np.array([1,0,1,0],dtype=bool)
b=np.array([1,1,1,0],dtype=bool)
np.logical_or(a,b)

array([ True,  True,  True, False])

In [101]:
np.logical_and(a,b)

array([ True, False,  True, False])

In [103]:
#Trigonometric func
a=np.arange(5)
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [104]:
np.log(a)

C:\Users\Sai\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [105]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [106]:
#basic reductions
np.sum(a)

10

In [107]:
a

array([0, 1, 2, 3, 4])

In [109]:
x=np.array([[1,2],[1,1]])
x

array([[1, 2],
       [1, 1]])

In [112]:
x.sum(axis=0) #column wise

array([2, 3])

In [113]:
x.sum(axis=1) #row wise

array([3, 2])

In [123]:
x=np.array([1,2,3,4])
x.argmin()   #index of minimum element

0

In [124]:
x.argmax()  #index of miminum element

3

In [125]:
x.min()

1

In [126]:
x.max()

4

In [128]:
#Logical operations
np.all([True,False,True])  #returns true if all are true

False

In [130]:
np.any([True,False,True]) #Returns true if any true

True

In [132]:
a=np.zeros((50,50))

In [133]:
np.any(a!=0)

False

In [144]:
#Broadcasting
a=np.tile(np.arange(0,40,10),(3,1))
a

array([[ 0, 10, 20, 30],
       [ 0, 10, 20, 30],
       [ 0, 10, 20, 30]])

In [145]:
a=a.T
a

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [146]:
b=np.array([0,1,2])
b

array([0, 1, 2])

In [147]:
a+b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [149]:
a=np.arange(0,40,10)
a

array([ 0, 10, 20, 30])

In [151]:
a.shape

(4,)

In [152]:
a=a[:,np.newaxis]
a

array([[ 0],
       [10],
       [20],
       [30]])

In [153]:
a.shape

(4, 1)

In [154]:
a+b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [155]:
b

array([0, 1, 2])

In [157]:
#Flattening
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [159]:
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [160]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [162]:
a.shape

(2, 3)

In [166]:
a=a.ravel()
a

array([1, 2, 3, 4, 5, 6])

In [167]:
a.shape

(6,)

In [168]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [170]:
#Dimensions

In [171]:
z=np.array([1,2,3]) #1D

In [176]:
z[:,np.newaxis] #2D

array([[1],
       [2],
       [3]])

In [178]:
a=np.arange(4*3*2).reshape(4,3,2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])